print(3+8)
print(10%5)
print(type({"name":"Ben"}))
print(3+4)
print(3-4)
print(3*4)
print(3/4)
print(3**4)
print(3//4)
print("Benjamin")
print("Keating")
print("United States")
print("I am learning Python")
print(type(10))
print(type(3.14))
print(type(9.81))
print(type(4-4j))
print(type(['Asabeneh','Python','Finland']))
print(type("ben"))
print(type("keating"))
print(type(True))
print(((6-3)**2)+((6-5)**2)**0.5)

